import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Canvas} from "@react-three/fiber";
import {Model} from "@/pages/components/Model";
import {Suspense} from "react";
import {OrbitControls} from "@react-three/drei";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div>xxxx</div>
          <Canvas
              camera={{ position: [2, 0, 12.25], fov: 15 }}
              style={{
                  backgroundColor: '#111a21',
                  width: '100vw',
                  height: '100vh',
              }}
          >
              <ambientLight intensity={1.25} />
              <ambientLight intensity={0.1} />
              <directionalLight intensity={0.4} />
              <Suspense fallback={null}>
                  <Model position={[0.025, -0.9, 1]} />
              </Suspense>
              <OrbitControls />
          </Canvas>
{/*          <Canvas
              camera={{
                  fov: 90,
                  position: [0, 0, 3],
              }}
          >
              <ambientLight intensity={0.1} />
              <directionalLight position={[1, 1, 1]} intensity={0.8} />
               !
              <Model />
          </Canvas>*/}
      </main>
    </>
  )
}
